// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB15omqgnpZN46kuTrlXi7f_FutkC5MqyA',
    appId: '1:111160179496:web:2bc13492ed961224812e1d',
    messagingSenderId: '111160179496',
    projectId: 'tuddo-gramado-app',
    authDomain: 'tuddo-gramado-app.firebaseapp.com',
    storageBucket: 'tuddo-gramado-app.appspot.com',
    measurementId: 'G-CYM1P69CX9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNFCBCw-ynEYG6TwG2sCNIB255MjJ63Ls',
    appId: '1:111160179496:android:11ea2800461f6edf812e1d',
    messagingSenderId: '111160179496',
    projectId: 'tuddo-gramado-app',
    storageBucket: 'tuddo-gramado-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAkkiHmBMDG-mFHaQEVcIf2iEzNLj3jgU',
    appId: '1:111160179496:ios:330168724e9e6dbc812e1d',
    messagingSenderId: '111160179496',
    projectId: 'tuddo-gramado-app',
    storageBucket: 'tuddo-gramado-app.appspot.com',
    androidClientId: '111160179496-o4sog4tf47tjlug2s15pdhpsdekj22o1.apps.googleusercontent.com',
    iosClientId: '111160179496-jr2oh7o5bdomidchrt8l04mqfs3akt06.apps.googleusercontent.com',
    iosBundleId: 'com.tuddo.tuddo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAkkiHmBMDG-mFHaQEVcIf2iEzNLj3jgU',
    appId: '1:111160179496:ios:0411e930da9ae077812e1d',
    messagingSenderId: '111160179496',
    projectId: 'tuddo-gramado-app',
    storageBucket: 'tuddo-gramado-app.appspot.com',
    iosBundleId: 'com.example.appTuddoGramado',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB15omqgnpZN46kuTrlXi7f_FutkC5MqyA',
    appId: '1:111160179496:web:812b8766dcef26e2812e1d',
    messagingSenderId: '111160179496',
    projectId: 'tuddo-gramado-app',
    authDomain: 'tuddo-gramado-app.firebaseapp.com',
    storageBucket: 'tuddo-gramado-app.appspot.com',
    measurementId: 'G-MFQWM12E07',
  );
}
